### PR TITLE
feat: add S3 Bucket creation and deployment in CloudFront with automatic cache update

### PR DESCRIPTION
**Pull request by victordobryi**

### CODE REVIEW

**Comment by victordobryi** [comment]
The functionality is fully implemented

**Comment by zavyalovdmitry** [comment]
Hi, could you provide the link to your cloudfront website?

**Comment by victordobryi** [comment]
> Hi, could you provide the link to your cloudfront website?

S3 - http://aws-shop-from-cdk.s3-website-us-east-1.amazonaws.com/ CloudFront - https://d1wkbdk2qc6sd4.cloudfront.net/

**Comment by victordobryi** [comment]
> Hi, could you provide the link to your cloudfront website?

all links in readme file in task-2 branch :)

**Pull request merged**
